# Generated by Django 4.0.8 on 2022-12-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qos',
            name='async_view',
        ),
        migrations.RemoveField(
            model_name='qos',
            name='ddosify_count',
        ),
        migrations.RemoveField(
            model_name='qos',
            name='ddosify_duration',
        ),
        migrations.RemoveField(
            model_name='qos',
            name='ddosify_timeout',
        ),
        migrations.RemoveField(
            model_name='qos',
            name='ping_algorithm',
        ),
    ]
